prototype(TYPO3.TypoScript:Testing.Throwing).@class = 'TYPO3\\TypoScript\\Tests\\Functional\\TypoScriptObjects\\Fixtures\\TypoScriptObjects\\ThrowingImplementation'

exceptionHandler.eelExpressionInProperty = TYPO3.TypoScript:Array {
	start = 'Start'
	error = TYPO3.TypoScript:Collection {
		collection = ${Testing.Utility.throwException()}

		@exceptionHandler = 'TYPO3\\TypoScript\\Core\\ExceptionHandlers\\PlainTextHandler'
	}
	end = 'End'
}

exceptionHandler.eelExpressionInOverride = TYPO3.TypoScript:Array {
	start = 'Start'
	error = TYPO3.TypoScript:Collection {
		@context.myCollection = ${Testing.Utility.throwException()}
		collection = ${myCollection}
		itemName = 'item'

		@exceptionHandler = 'TYPO3\\TypoScript\\Core\\ExceptionHandlers\\PlainTextHandler'
	}
	end = 'End'
}


exceptionHandler.nestedHandlerIsEvaluated = TYPO3.TypoScript:Value {
	value = TYPO3.TypoScript:Testing.Throwing {
		shouldThrow = TRUE
		@exceptionHandler = 'TYPO3\\TypoScript\\Core\\ExceptionHandlers\\PlainTextHandler'
	}
}